apiVersion: skaffold/v2beta19
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - context: src
    image: saxml-proxy 
    sync:
      infer:
      - '**/*.py'
# defines the Kubernetes manifests to deploy on each run
deploy:
   kustomize:
      paths:
      - manifests
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}