apiVersion: skaffold/v2beta19
kind: Config
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - context: src/saxml_proxy
    image: saxml-proxy 
    sync:
      infer:
      - '**/*.py'
  - context: src/checkpoint_converter
    image: checkpoint-converter
# defines the Kubernetes manifests to deploy on each run
deploy:
   kustomize:
      paths:
      - saxml_manifests
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {
      machineType: "e2-highcpu-32",
      timeout: "3600s"
    }